[WIP] Pr3di
Vocaluxe/Vocaluxe pull request #229
Opened 2016-11-21 16:51 UTC by Pr3di

Song selection Screen with Records
Party Mode with Rounds

2016-11-21 20:16 UTC, lukeIam commented
@Pr3di Buildconfig should now be fine

2016-11-22 12:11 UTC, flokuep requested changes
Thank you very much for your work! These are some nice additions to vocaluxe :) I've done a first review by reading you code, I will testing everything later...

2016-11-22 12:11 UTC, flokuep commented on PartyModes/PartyModeChallengeRounds/CPartyScreenChallengeRoundsConfig.cs
> +using System.Windows.Forms;
Why do you need them?

2016-11-22 12:11 UTC, flokuep commented on PartyModes/PartyModeChallengeRounds/CPartyScreenChallengeRoundsConfig.cs
> +            _SelectSlides[_SelectSlideRefillJokers].AddValue(CBase.Language.Translate("TR_BUTTON_NO", PartyModeID));
Should be enough to add "TR_BUTTON_NO". Befor drawing, it will be translated (I guees).

2016-11-22 12:11 UTC, flokuep commented on PartyModes/PartyModeChallengeRounds/CPartyScreenChallengeRoundsConfig.cs
> +            _PartyMode.GameData.RefillJokers = (_SelectSlides[_SelectSlideRefillJokers].Selection == 1) ? true : false;
_PartyMode.GameData.RefillJokers = _SelectSlides[_SelectSlideRefillJokers].Selection == 1; Will have the same effect ;) This will be evaluated to true or false.

2016-11-22 12:11 UTC, flokuep commented on VocaluxeLib/Menu/SongMenu/CSongMenuListRecord.cs
> +            if (_RecordStyle.Equals(ERecordStyle.RECORDSTYLE_ALL))
You could check enums with == operator

2016-11-22 12:11 UTC, flokuep commented on VocaluxeLib/Menu/SongMenu/CSongMenuListRecord.cs
> +
Maybe you could remove some brackets here? I guess you could write this a bit shorter (but still readable)... eg.
String recordName = score.Name;
if(_RecordStyle == ERecordStyle.RECORDSTYLE_DIFFICULTY)
    recordName += score.Difficulty

2016-11-22 12:11 UTC, flokuep commented on VocaluxeLib/VocaluxeLib.csproj
> +    <WCFMetadata Include="Service References\" />
What is this one?

2016-11-22 12:12 UTC, flokuep commented
Off topic: This review feature seems to be really nice?

2016-11-22 14:15 UTC, Pr3di commented on VocaluxeLib/VocaluxeLib.csproj
> +    <WCFMetadata Include="Service References\" />
I dont know VS did that ^^
I deleted it already

2016-11-22 14:17 UTC, Pr3di commented on PartyModes/PartyModeChallengeRounds/CPartyScreenChallengeRoundsConfig.cs
> +            _SelectSlides[_SelectSlideRefillJokers].AddValue(CBase.Language.Translate("TR_BUTTON_NO", PartyModeID));
Yes your right

2016-11-22 14:18 UTC, Pr3di commented on PartyModes/PartyModeChallengeRounds/CPartyScreenChallengeRoundsConfig.cs
> +            _PartyMode.GameData.RefillJokers = (_SelectSlides[_SelectSlideRefillJokers].Selection == 1) ? true : false;
yes it look better that way

2017-11-22 18:27 UTC, flokuep commented
Thanks for apply my suggestions.

There still seems CSongMenuListRecord.cs somewhere in your project (that's the reason why appveyor failed). Could you check this?

2017-11-22 18:34 UTC, flokuep requested changes
There are some unnecessary files checked into git, could you please remove them?
* PitchTracker/bin
* Vocaluxe.VC.db

Also ChallengeRounds Files are still in Output/PartyModes. After integrating your changes into ChallengeMode this special mode was removed ;)

2017-11-22 18:34 UTC, flokuep commented on VocaluxeLib/Menu/SongMenu/CSongMenuList.cs
> +
Here is some uncommented code... Could you remove it if you don't need it anymore?

2017-11-23 08:27 UTC, lukeIam commented
There still seems CSongMenuListRecord.cs somewhere in your project (that's
the reason why appveyor failed). Could you check this?


Looks like there's a reference left in `VocaluxeLib\VocaluxeLib.csproj`

2017-11-24 17:49 UTC, Pr3di commented
So now everything should be done

2017-11-25 18:40 UTC, lukeIam commented
Thanks for working on this!

The song menu is misplaced (at least when I tired the current code):
![image](https://user-images.githubusercontent.com/5115160/33233568-4c3fc968-d218-11e7-9d22-e008628fb8c6.png)

2017-11-25 19:07 UTC, lukeIam commented
Do have to enable the highscore view somewhere in the config?

2017-11-25 21:28 UTC, flokuep commented
Song options menu isnt't bind to song menu, so it's the same for every style (that would be the issue) - We need to find a good solution for tiles and list view.

Highscores are only available for list style I guess, @lukeIam.

2017-11-26 03:37 UTC, Pr3di commented
Yeah i could try to edit the Tiles view so that only 4x4 Tiles are shown. Then the video could be the same size as in List view and i could add the Highscores there too.

The other possibility would be to create two different menus.

2017-11-26 07:56 UTC, flokuep commented
I'm sorry; This wouldn't work. There will be too less space for this song menu then. We need to think about a bigger solution for adding records to tiles-menu (see #312).

I've found another problem with your list-menu. Small view isn't implemented correctly; We use this for showing playlists/having space for jokers in party modes.
![screenshot](https://user-images.githubusercontent.com/1449832/33238162-a1926d3e-d287-11e7-9fb3-40ae9ac684f4.png)

2017-11-27 19:36 UTC, Pr3di commented
k i should start test all these features i never use :D 
So i added a SmallView for the ListView where the videosize switches back to the smaller size and no record are shown as long as the playlist is open. How do you like that?

I think for playlist it is good but for the PartyMode i don't like i that way because i want to have the records and the larger video. Also the Jokers don't really need that much space. So i would need a third mode for the PartyMode. Actually in PartyMode you dont really need a List at all cause you can't change songs anyway.

2024-11-11 12:59 UTC, marwin89 commented
@flokuep , can we close this pr? It's almost eight years open and I guess the commits don't fit to the latest changes anymore.

2024-11-11 14:42 UTC, flokuep commented
Yep, please reopen if this still should be merged. Beforehand all conflicts need to be resolved and theme changes adjusted.

2024-11-11 14:42 UTC, closed without merging