refactor: german translation
Vocaluxe/Vocaluxe pull request #576
Opened 2022-02-21 16:38 UTC by hedwiggggg

I have corrected and improved the German translation + all missing translations should be there now.

2022-02-21 17:53 UTC, Stefan1200-de requested changes
I like many changes, but some I don't like (because they are misleading or wrong). To much to list them here now. As soon as I have some more time, I would make some more detailed suggestions, if that is okay for you.

2022-02-21 18:23 UTC, hedwiggggg commented
sure!

2022-10-29 15:56 UTC, Stefan1200-de commented
Ich gehe mal davon aus, wenn du eine deutsche Übersetzung vorschlägst, das wir hier auch auf Deutsch darüber diskutieren können. 

Hat etwas gedauert, aber heute habe ich mir über deine guten Vorschläge Gedanken gemacht. Hier meine Anmerkungen oder Vorschläge:

`<string name="TR_GAMEMODE_SHORTSONG">Kurz</string>`
Hier finde ich die aktuelle Variante mit "Kurz-Version" deutlicher.

```
<string name="TR_RATING_VOCAL_HERO">Superstar</string>
<string name="TR_RATING_SUPERSTAR">Hit-Künstler</string>
<string name="TR_RATING_LEAD_SINGER">Sänger</string>
```
Superstar sollte man wohl bei TR_RATING_SUPERSTAR stehen lassen, wenn es im Englischen auch so heißt.
Das man bei "Vocal Hero" aber ein besseres deutsches Wort finden kann, ist unstrittig. Meine Vorschläge für "Vocal Hero" wären:
- Hit-Gigant (passend zu Hit-Künstler).
- Megastar
- Virtuose oder Gesangsvirtuose

`<string name="TR_CONFIG_COVERLOADING_ONDEMAND">Bei Anforderung</string>`
Ich bin mir gerade nicht sicher, wie "ON DEMAND" funktioniert. Ich glaube da wird das Cover erst geladen, wenn das Lied abgespielt wird. In dem Fall finde ich "Bei Bedarf" passt hier besser.

`<string name="TR_CONFIG_TIMERMODE_CURRENT">Aktuelle Zeit</string>`
Hmm, klingt hier vielleicht "Aktuelle Position" besser?

`<string name="TR_CONFIG_HIGHSCORE_LIST_BEST">Beste auflisten</string>`
Das entspricht nicht der Funktion. Es ist ja gemeint, dass jeder Spieler nur einmal in der Bestenliste angezeigt wird, aber mit dem besten Ergebnis für das Lied. Vermutlich ist "Bestes Spielerergebnis" oder "Beste Spielerpunktzahl" die bessere Übersetzung.

`<string name="TR_SCREENSING_BUTTON_SKIP">Überspringen</string>`
Macht "Lied überspringen" nicht deutlicher, was gemeint ist? Oder gab es einen anderen Grund für die Änderung (z.B. Textlänge)?

`<string name="TR_SCREENOGAME_TIMERMODE">Timer-Modus</string>`
Hier finde ich "Zeit-Modus" schöner. Warum findest du hier "Timer-Modus" besser?

`<string name="TR_SCREENORECORD_DEVICE">Gerät</string>`
Ich frage mich gerade, ob hier "Mikrofon" oder "Aufnahmegerät" nicht sogar noch besser wäre.

```
<string name="TR_SCREENOTHEME_THEME">Theme</string>
<string name="TR_SCREENOTHEME_OPTIONS">Darstellungs-Einstellungen</string>
<string name="TR_SCREENO_BUTTON_THEME">Darstellung</string>
```
Eventuell sollten wir hier die selben Begrifflichkeiten verwenden?

2023-12-28 20:22 UTC, flokuep commented
@hedwiggggg @Stefan1200-de Ich würde den PR erstmal schließen. Die Übersetzungen müssen über Transifex angepasst werden, die Strings dort sind führend.

2023-12-28 20:22 UTC, closed without merging