[PartyMode] TicTacToe - improvements
Vocaluxe/Vocaluxe pull request #636
Opened 2023-12-22 16:39 UTC by damienlaguerre

### Summary
Try to fix somes mistakes in the game mode.

### What does this PR do?

- Fix: Teams with more than 2 players. Only the first and the second players are chosen.
- Add: The number of jockers can be configured.
- Improve: The player random selection.

### Screenshots / Video
![Capture d’écran 2023-12-22 173912](https://github.com/Vocaluxe/Vocaluxe/assets/25153590/6a55cc77-f44a-44b4-9aa8-9874642c092d)

![Capture d’écran 2023-12-22 173720](https://github.com/Vocaluxe/Vocaluxe/assets/25153590/bf2664ab-67bd-4a4c-8517-a49c41a266f2)

2023-12-23 09:31 UTC, marwin89 commented
Hi Damien, welcome to vocaluxe! this looks like a good contribution. 👋 :)
Can someone do a short QA and review? (@Stefan1200-de) I'm overloaded with other tasks (UI/Logo design, etc.) right now.

2023-12-23 13:38 UTC, flokuep requested changes
Thank you very much for your (first) contribution :) I really like the improvements you've added to that party mode. I've found some smaller things that can be improved within you code, I'd be happy if you could have a look on it (most of these things are also mentioned within the sonarqube report).

2023-12-23 13:38 UTC, flokuep commented on PartyModes/PartyModeTicTacToe/CPartyScreenTicTacToeMain.cs
> +                if (next == true)
could be simplyfied to if (next)

2023-12-23 13:38 UTC, flokuep commented on PartyModes/PartyModeTicTacToe/CPartyScreenTicTacToeMain.cs
> +            lock (syncLock)
Could you explain why a lock is necessary here?

2023-12-23 13:38 UTC, flokuep commented on PartyModes/PartyModeTicTacToe/CPartyScreenTicTacToeMain.cs
> +            if (_PartyMode.GameData.ProfileIDsTeam1.Count > 0 && (teamNr == 0 || teamNr == -1))
I'd suggest to extract some code here to reduce duplicated lines, I guess a new method with Profile-TeamCount, teamNr and next would be working. Return value is ne id of the next player.

2023-12-23 13:38 UTC, flokuep commented on PartyModes/PartyModeTicTacToe/CPartyScreenTicTacToeMain.cs
> +        int idPlayer1 = 0;
Should be private fields I guess?

2023-12-23 13:38 UTC, flokuep commented on PartyModes/PartyModeTicTacToe/CPartyScreenTicTacToeConfig.cs
> +            _SelectSlides[_SelectSlideNumJockers].AddValue(3);
Could be improved by using a for-loop (or maybe AddValues can be used, not totally sure about it).

2023-12-23 13:38 UTC, flokuep commented on PartyModes/PartyModeTicTacToe/CPartyScreenTicTacToeNames.cs
> +            _PartyMode.GameData.NumPlayerTeam1 = _PartyMode.GameData.ProfileIDsTeam1.Count();
There is a Count property that could be used instead of the method I guess.

2023-12-23 18:55 UTC, damienlaguerre commented
Thanks for your messages! 
I've modified the code thanks to your feedback.
I hope you like it.

2023-12-23 19:01 UTC, damienlaguerre commented on PartyModes/PartyModeTicTacToe/CPartyScreenTicTacToeMain.cs
> +            lock (syncLock)
Without this, Random isn't really effective. It returns the same number for both teams at the start of the round.
If you know of a better way to generate a random int I'd love to hear from you :)

2023-12-24 04:45 UTC, flokuep approved these changes

2023-12-24 04:45 UTC, flokuep commented
Yes, I like them :) Sonar ist also mentioning the random-problematic, so that's fine I guess. PR is merged and changes will be included in the next nightly build (within a few minutes)

2023-12-24 04:45 UTC, merged