update readme
Vocaluxe/Vocaluxe pull request #720
Opened 2024-11-07 10:50 UTC by marwin89

add link to milestones and game design document

2024-11-13 09:14 UTC, flokuep requested changes

2024-11-13 09:14 UTC, flokuep commented on README.md
> +Check out [milestones](https://github.com/Vocaluxe/Vocaluxe/milestones) or our [Game Design Document](https://docs.google.com/document/d/1mNn92ezVH63pVVJoIqN1hjmWTX0L_jLb6bPYtGTl8EQ/edit?tab=t.0#head
Should be changed as soon as #724 is merged.

2024-11-13 09:14 UTC, flokuep commented on README.md
>  ## 4. Help & Support
Maybe add discord here?

2024-11-14 08:23 UTC, marwin89 commented on README.md
> +Check out [milestones](https://github.com/Vocaluxe/Vocaluxe/milestones) or our [Game Design Document](https://docs.google.com/document/d/1mNn92ezVH63pVVJoIqN1hjmWTX0L_jLb6bPYtGTl8EQ/edit?tab=t.0#head
link is updated ✅

2024-11-14 08:24 UTC, marwin89 commented
@flokuep : link is updated please merge

2024-11-14 08:58 UTC, flokuep approved these changes

2024-11-14 08:59 UTC, merged