Add Rap-Voca and GRaff844 to Credits
Vocaluxe/Vocaluxe pull request #742
Opened 2024-11-29 11:20 UTC by marwin89

Add Rap-Voca and GRaff844 to Credits, cleand up Art/Graphics section

2024-11-30 18:08 UTC, flokuep requested changes

2024-11-30 18:08 UTC, flokuep commented on Vocaluxe/Screens/CScreenCredits.cs
> -            AddText("Markus Bohning (2012)", textSize, EStyle.Normal, 0);
Why did you remove these three? Guess they did at least some coding?

2024-12-01 11:44 UTC, marwin89 commented on Vocaluxe/Screens/CScreenCredits.cs
> -            AddText("Markus Bohning (2012)", textSize, EStyle.Normal, 0);
yes, my fault, I wanted to copy paste them to programmers section, but seem to missed it

2024-12-01 12:33 UTC, flokuep approved these changes

2024-12-01 12:33 UTC, merged